name: FirePlugin
version: ${project.version}
main: com.f1remoon.fireplugin.FirePlugin
api-version: 1.13
authors: [F1remoon]
description: Burn it down
website: f1remoon.com
commands:
  fire:
    usage: /<command> <x> <y> <z> [height] [ticks]
    description: Make fire line
    permission: fireplugin.create.line
  explode:
    usage: /<command> <x> <y> <z> [power]
    description: Make environment friendly boom
    permission: fireplugin.create.explosion
