name: FirePlugin
version: ${project.version}
main: com.f1remoon.fireplugin.FirePlugin
api-version: 1.13
authors: [F1remoon]
description: Burn it down
website: f1remoon.com
commands:
  fire:
    usage: /<command> <x> <y> <z> [height] [ticks]
    description: Make fire line
    permission: fireplugin.create.line
  explode:
    usage: /<command> <x> <y> <z> [power]
    description: Make environment friendly boowm
    permission: fireplugin.create.explosion
  dispenser-fire:
    usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2> [height] [ticks]
    description: Finds all dispensers with up position and performs fireshow
    permission: fireplugin.create.line.sequence

